services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: bidbattle
      POSTGRES_PASSWORD: bidbattle
      POSTGRES_DB: bidbattle
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './db/data'
